#!/bin/sh
DAEMON=/usr/sbin/hostapd
NAME=hostapd
DESC="HOSTAP Daemon"
ARGS="/etc/hostapd.conf -B"

test -f $DAEMON || exit 0

[ -r /etc/default/hostapd ] && . /etc/default/hostapd

set -e

case "$HOSTAPD_ENABLE" in
	[Nn]*)
		exit 0
		;;
esac

case "$1" in
    start)
	echo "Enabling AP interface"
	iw phy0 interface add uap0 type __ap
	ifup uap0
	echo -n "Starting $DESC: "
	start-stop-daemon -S -x $DAEMON -- $ARGS
	echo "$NAME."
	;;
    stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x $DAEMON
	echo "$NAME."
	echo "Disabling AP interface"
	ifdown uap0
	iw uap0 del
	;;
    *)
	echo "Usage: $0 {start|stop}"
	exit 1
	;;
esac

exit 0
